name: URL Check

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Create URL check script
        run: |
          cat > url-check.js << 'EOF'
          const fetch = require('node-fetch');
          
          async function checkUrl() {
            try {
              // Get API URL from environment variable
              const baseUrl = process.env.VERCEL_BASE_URL || 'https://lifetime-pickle-bot.vercel.app';
              
              console.log(`Checking base URL: ${baseUrl}`);
              
              // Try different endpoints
              const endpoints = [
                '/api',
                '/api/schedule',
                '/api/update-schedule',
                '/api/test'
              ];
              
              for (const endpoint of endpoints) {
                const url = `${baseUrl}${endpoint}`;
                console.log(`\nTesting endpoint: ${url}`);
                
                try {
                  const response = await fetch(url);
                  console.log(`Status: ${response.status}`);
                  
                  try {
                    const text = await response.text();
                    console.log(`Response (first 200 chars): ${text.substring(0, 200)}...`);
                  } catch (e) {
                    console.log(`Could not read response: ${e.message}`);
                  }
                } catch (e) {
                  console.log(`Error fetching ${url}: ${e.message}`);
                }
              }
              
              console.log("\nURL check completed");
            } catch (error) {
              console.error("Error in URL check:", error);
              throw error;
            }
          }
          
          checkUrl()
            .then(() => console.log('Done'))
            .catch(err => {
              console.error('Failed:', err);
              process.exit(1);
            });
          EOF
          
          echo "Verifying url-check.js was created:"
          ls -la
          cat url-check.js
      
      - name: Install dependencies
        run: npm install node-fetch@2
      
      - name: Run URL check
        env:
          VERCEL_BASE_URL: ${{ secrets.VERCEL_BASE_URL || 'https://lifetime-pickle-bot.vercel.app' }}
        run: node url-check.js

