name: Weekly Pickleball Schedule Scraper

on:
  schedule:
    # Run every Sunday at 1:00 AM UTC (adjust as needed)
    - cron: '0 1 * * 0'
  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      # Create package.json file directly in the workflow
      - name: Create package.json
        run: |
          cat > package.json << 'EOF'
          {
            "name": "lifetime-scraper",
            "version": "1.0.0",
            "description": "Weekly scraper for Lifetime Pickleball schedule",
            "main": "scraper.js",
            "type": "module",
            "scripts": {
              "start": "node scraper.js"
            },
            "dependencies": {
              "puppeteer-core": "^21.0.0",
              "@sparticuz/chromium": "^121.0.0",
              "dotenv": "^16.0.3",
              "node-fetch": "^3.3.1"
            }
          }
          EOF
          
          # Verify the file was created
          cat package.json
          
      - name: Install dependencies
        run: npm install
        
      - name: Run scraper
        env:
          LIFETIME_USERNAME: ${{ secrets.LIFETIME_USERNAME }}
          LIFETIME_PASSWORD: ${{ secrets.LIFETIME_PASSWORD }}
          VERCEL_API_URL: ${{ secrets.VERCEL_API_URL }}
          VERCEL_API_KEY: ${{ secrets.VERCEL_API_KEY }}
        run: node scraper.js




