name: Weekly Pickleball Schedule Scraper

on:
  schedule:
    # Run every Sunday at 1:00 AM UTC (adjust as needed)
    - cron: '0 1 * * 0'
  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run scraper
        env:
          LIFETIME_USERNAME: ${{ secrets.LIFETIME_USERNAME }}
          LIFETIME_PASSWORD: ${{ secrets.LIFETIME_PASSWORD }}
          VERCEL_API_URL: ${{ secrets.VERCEL_API_URL }}
          VERCEL_API_KEY: ${{ secrets.VERCEL_API_KEY }}
        run: node scraper.js


